"""Shared shell completion utilities"""

import os
from pathlib import Path

import typer


TOOLS = ["report", "commit", "review", "benchmark", "mock", "translate", "port"]


def detect_shell() -> str:
    """Detect shell from environment"""
    shell_env = os.environ.get("SHELL", "")
    if "bash" in shell_env:
        return "bash"
    elif "zsh" in shell_env:
        return "zsh"
    elif "fish" in shell_env:
        return "fish"
    return "unknown"


def install_all_bash_completion() -> None:
    """Install bash completion for all tools"""
    completion_dir = Path.home() / ".bash_completions"
    completion_dir.mkdir(exist_ok=True)

    script_lines = [
        "# Toolkit bash completions",
        "# Generated by: toolkit completion install",
        "",
    ]

    for tool in TOOLS:
        script_lines.extend([
            f"# {tool}",
            f"_complete_{tool}() {{",
            f"    local IFS=$'\\n'",
            f"    COMPREPLY=( $( env COMP_WORDS=\"${{COMP_WORDS[*]}}\" \\",
            f"                   COMP_CWORD=$COMP_CWORD \\",
            f"                   _{tool.upper()}_COMPLETE=complete_bash $1 ) )",
            f"    return 0",
            f"}}",
            f"complete -o default -F _complete_{tool} {tool}",
            "",
        ])

    script = "\n".join(script_lines)
    completion_file = completion_dir / "toolkit.sh"
    completion_file.write_text(script)

    bashrc = Path.home() / ".bashrc"
    source_line = f"source {completion_file}"

    typer.echo(f"✅ Created: {completion_file}")

    if bashrc.exists():
        content = bashrc.read_text()
        if source_line not in content:
            typer.echo(f"\n📝 Adding to ~/.bashrc...")
            with open(bashrc, "a") as f:
                f.write(f"\n# Toolkit bash completion\n")
                f.write(f"{source_line}\n")
            typer.echo(f"✅ Added to ~/.bashrc")
            typer.echo(f"\nRun: source ~/.bashrc or restart terminal")
        else:
            typer.echo(f"✅ Already configured in ~/.bashrc")


def install_all_zsh_completion() -> None:
    """Install zsh completion for all tools"""
    completion_dir = Path.home() / ".zsh" / "completions"
    completion_dir.mkdir(parents=True, exist_ok=True)

    for tool in TOOLS:
        script = f"""#compdef {tool}

_{tool}_completion() {{
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[{tool}] )) && return 1

    response=("${{(@f)$(env COMP_WORDS="${{words[*]}}" COMP_CWORD=$((CURRENT-1)) _{tool.upper()}_COMPLETE=complete_zsh {tool})}}")

    for type key descr in ${{response}}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}}

compdef _{tool}_completion {tool}"""

        completion_file = completion_dir / f"_{tool}"
        completion_file.write_text(script)
        typer.echo(f"✅ Created: {completion_file}")

    typer.echo(f"\nAdd to ~/.zshrc:")
    typer.echo(f"    fpath=({completion_dir} $fpath)")
    typer.echo("    autoload -Uz compinit && compinit")


def install_all_fish_completion() -> None:
    """Install fish completion for all tools"""
    completion_dir = Path.home() / ".config" / "fish" / "completions"
    completion_dir.mkdir(parents=True, exist_ok=True)

    for tool in TOOLS:
        script = f'complete --command {tool} --no-files --arguments \'(env _{tool.upper()}_COMPLETE=complete_fish _TYPER_COMPLETE_FISH_ACTION=get-args _TYPER_COMPLETE_ARGS=(commandline -cp) {tool})\''
        completion_file = completion_dir / f"{tool}.fish"
        completion_file.write_text(script)
        typer.echo(f"✅ Created: {completion_file}")

    typer.echo("\nRestart terminal or run: source ~/.config/fish/config.fish")


def show_bash_completion() -> str:
    """Generate bash completion script"""
    lines = [
        "# Toolkit bash completions",
        "# Usage: source this file or add to ~/.bashrc",
        "",
    ]

    for tool in TOOLS:
        lines.extend([
            f"# {tool}",
            f"_complete_{tool}() {{",
            f"    local IFS=$'\\n'",
            f"    COMPREPLY=( $( env COMP_WORDS=\"${{COMP_WORDS[*]}}\" \\",
            f"                   COMP_CWORD=$COMP_CWORD \\",
            f"                   _{tool.upper()}_COMPLETE=complete_bash $1 ) )",
            f"    return 0",
            f"}}",
            f"complete -o default -F _complete_{tool} {tool}",
            "",
        ])

    return "\n".join(lines)


def show_zsh_completion() -> str:
    """Generate zsh completion script"""
    lines = [
        "# Toolkit zsh completions",
        "# Add to fpath and run: autoload -Uz compinit && compinit",
        "",
    ]

    for tool in TOOLS:
        lines.extend([
            f"#compdef {tool}",
            f"_{tool}_completion() {{",
            f"    local -a completions",
            f"    local -a completions_with_descriptions",
            f"    local -a response",
            f"    (( ! $+commands[{tool}] )) && return 1",
            f"    response=(\"${{(@f)$(env COMP_WORDS=\"${{words[*]}}\" COMP_CWORD=$((CURRENT-1)) _{tool.upper()}_COMPLETE=complete_zsh {tool})}}\")",
            f"    for type key descr in ${{response}}; do",
            f"        if [[ \"$type\" == \"plain\" ]]; then",
            f"            if [[ \"$descr\" == \"_\" ]]; then",
            f"                completions+=(\"$key\")",
            f"            else",
            f"                completions_with_descriptions+=(\"$key\":\"$descr\")",
            f"            fi",
            f"        fi",
            f"    done",
            f"    if [ -n \"$completions_with_descriptions\" ]; then",
            f"        _describe -V unsorted completions_with_descriptions -U",
            f"    fi",
            f"    if [ -n \"$completions\" ]; then",
            f"        compadd -U -V unsorted -a completions",
            f"    fi",
            f"}}",
            f"compdef _{tool}_completion {tool}",
            "",
        ])

    return "\n".join(lines)


def show_fish_completion() -> str:
    """Generate fish completion script"""
    lines = [
        "# Toolkit fish completions",
        "# Note: For fish shell, each tool needs its own completion file.",
        "# Run 'tools completion' to install all completion files.",
        "",
    ]

    for tool in TOOLS:
        lines.append(
            f'complete --command {tool} --no-files --arguments \'(env _{tool.upper()}_COMPLETE=complete_fish _TYPER_COMPLETE_FISH_ACTION=get-args _TYPER_COMPLETE_ARGS=(commandline -cp) {tool})\''
        )

    return "\n".join(lines)
